language: python
cache: pip
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo pip install update
  - sudo pip install redis
script:
  - python LoadGenRP.py
